### ISSUE TITLE
Review code of NiiVue Jupyter notebook integration in IPyNiiVue

### ISSUE THREAD

**Issue by cdrake** [niivue/ipyniivue#36]

**Comment by christian-oreilly** [comment]
I'll have a look at this. Let's add to this issue the integration into the CI of some linting validation at the same time. We can probably re-use directly the yaml  file from the PyLossless project for that:

```yaml
name: PEP8 Compliance, Spellcheck, & Docstring

on: pull_request

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: pip install -r requirements_testing.txt
    - name: Run flake8
      run: flake8 pylossless docs --exclude pylossless/__init__.py
    - name: Run Codespell
      run: codespell pylossless docs --skip docs/source/generated
    - name: Check Numpy Format Docstring
      run: pydocstyle pylossless
```
